[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."verify-background"]
  timeout = 900

[functions."verify-status"]
  timeout = 10

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
